runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: users.py

libraries: 
- name: flask
  version: "0.12"
# TODO: Import this third party library for use with app engine
# May need to upload to repo from https://github.com/pallets/flask-sqlalchemy
- name: Flask-SQLAlchemy
  version: "2.4.0" 

# references: 
# [1] https://cloud.google.com/appengine/docs/standard/python/quickstart 
# [2] https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27
# [3] https://cloud.google.com/appengine/docs/standard/python/tools/built-in-libraries-27