# app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: employee_recognition_api.views.main.app

libraries: 
- name: flask
  version: "0.12"

env_variables:
  ENV: 'dev'

# References: 
# [1] https://cloud.google.com/appengine/docs/standard/python/config/appref        re: use of env variables